# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageName: English
  languageCode: en-us
  weight: 1  # 낮은 숫자가 우선순위가 더 높음 (영어를 기본으로 설정)
  menu:
    main:
      - name: Introduction
        url: /en/
        weight: 10
      - name: Certification
        url: /en/publication/
        weight: 11
      - name: Award-winning
        url: /en/event/
        weight: 12
      - name: Technical Stack
        url: /en/post/
        weight: 13
      - name: Experience
        url: /en/experience/
        weight: 20
      - name: Blog
        url: /en/projects/
        weight: 30
      - name: Teaching
        url: /en/teaching/
        weight: 40

ko:
  languageName: 한국어
  languageCode: ko-kr
  weight: 2  # 한국어는 두 번째 언어
  menu:
    main:
      - name: 소개
        url: /ko/
        weight: 10
      - name: 자격증
        url: /ko/publication/
        weight: 11
      - name: 수상 경력
        url: /ko/event/
        weight: 12
      - name: 기술 스택
        url: /ko/post/
        weight: 13
      - name: 경험
        url: /ko/experience/
        weight: 20
      - name: 블로그
        url: /ko/projects/
        weight: 30
      - name: 강의
        url: /ko/teaching/
        weight: 40

  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
