# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageName: English
  languageCode: en-us
  contentDir: content/en  # 영어 컨텐츠 폴더 설정
  weight: 2  # 낮은 숫자가 우선순위가 더 높음
  menu:
    main:
      - name: Introduction
        url: /en/
        weight: 10
      - name: Certification
        url: /en/publication/
        weight: 11
      - parent: Certification
        name: 리눅스
        url: /en/publication/linux-master/
        weight: 12
      - parent: Certification
        name: sqld
        url: /en/publication/sqld/
        weight: 13
      - name: Award-winning
        url: /en/event/
        weight: 14
      - name: Technical Stack
        url: /en/post/
        weight: 15
      - name: Experience
        url: /en/experience/
        weight: 16
      - name: Blog
        url: /en/projects/
        weight: 17
      - name: Contact
        url: /en/teaching/
        weight: 18

ko:
  languageName: 한국어
  languageCode: ko-kr
  contentDir: content/ko  # 한국어 컨텐츠 폴더 설정
  weight: 1  # 한국어는 첫번째 언어로 설정
  menu:
    main:
      - name: 소개
        url: /ko/
        weight: 10
      - name: 자격증
        url: /ko/publication/
        weight: 11
      - parent: 자격증
        name: 리눅스
        url: /ko/publication/linux-master/
        weight: 12
      - parent: 자격증
        name: sqld
        url: /ko/publication/sqld/
        weight: 13
      - name: 수상 경력
        url: /ko/event/
        weight: 14
      - name: 기술 스택
        url: /ko/post/
        weight: 15
      - name: 경험
        url: /ko/experience/
        weight: 16
      - name: 블로그
        url: /ko/projects/
        weight: 17
      - name: 연락
        url: /ko/teaching/
        weight: 18

  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
