# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Introduction
    url: /
    weight: 10
  - name: Certification
    url: /publication/
    weight: 11
    identifier: certification
    hasChildren: true
    children:
      - name: 리눅스 마스터 2급
        url: /publication/linux-master/
      - name: SQLD
        url: /publication/sqld/
  - name: Award-winning
    url: event/
    weight: 12
  - name: Technical Stack
    url: post/
    weight: 13
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
